branch-defaults:
  master:
    environment: pitests-env
global:
  application_name: pitests
  default_ec2_keyname: aws-eb
  default_platform: PHP 5.6
  default_region: us-west-2
  profile: eb-cli
  sc: git
